# Generated by Django 3.1.3 on 2020-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronagevallen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronagevallen',
            name='positievegevallen',
            field=models.CharField(default='geen', max_length=50),
        ),
    ]
